name: use node event
on: [push]
jobs:
  use-node:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout
        uses: actions/checkout@v2
        with:
          repository: 'Ambition-J/wechart-web'
      - name: list fies in the repo
        run: |
          ls ${{github.workspace}}
      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # - name: run node script
      - run: |
          node -v 
          npm install -g typescript
          tsc -v
        