name: use secrets 
on: [push]
jobs:
  SECRET-ON-SSH:
    runs-on: ubuntu-latest
    steps:
      - name: use ssh action
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true # 发生错误时，停止执行以下的命令
          script: |
            pwd
            ls -l 
            touch secret.txt
            echo ${{secrets.MY_SECRET}} >> secret.txt